### ISSUE TITLE
Porting to Android Platform

### ISSUE THREAD

**Issue by cylof22** [GameTechDev/stardust_vulkan#5]
I am porting the stardust demo to the Android platform. Because of the limitation of the mobile platform, the maximal color attachment is 4, I change the implementation of the render_to_skybox_image by using the staging buffer and vkCmdCopyBufferToImage.  The method is also used in https://github.com/PacktPublishing/Vulkan-Cookbook/tree/master/Samples/Source%20Files/12%20Advanced%20Rendering%20Techniques/01-Drawing_a_skybox.  However, the result is bad. Only a yellow color image is show.

**Comment by ghost** [comment]
Hi @cylof22. You may want to check if your modification passes the validation layers. 

Currently we don't have any plans for port this application to Android.
However we will gladly accept any contributions!

As this issue is about the change not contained in this repository, I will close this issue now. 

Please reopen if you have any further developments.
